name: REPOSITORY-CHANGES
run-name: Something

on:
  workflow_dispatch:

jobs:

  get-config:
    name: Repositories GitOps
    runs-on: ubuntu-latest
    #env:
    #  GH_TOKEN: ${{ secrets.GITOPS_REPOS }}
    outputs:
      matrix-solutions: ${{ steps.solution-repos.outputs.SOLUTIONS }}

    steps:

      - name: Checkout GitOps
        uses: actions/checkout@v3

      - run: echo $(yq -V)

      - name: Get Solution Repo's
        id: solution-repos
        run: |
          soln="$(yq eval '.repositories.solutions' repositories.yml -o=json | jq -r 'tostring')"
          echo '{"include":'$soln'}'
          echo "SOLUTIONS='{\"include\":'$soln'}'" >> $GITHUB_OUTPUT

  make-changes:
    name: Make changes to repos
    needs: [get-config]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.get-config.outputs.matrix-solutions) }}

    steps:

      - name: Check repo exists
        run: echo "${{ matrix.repo }}"

