name: REPOSITORY-CHANGES
run-name: Event ${{ github.event_name }} run by ${{ github.actor }} 

on:
  workflow_dispatch:

jobs:

  get-config:
    name: Repositories GitOps
    runs-on: ubuntu-latest
    #env:
    #  GH_TOKEN: ${{ secrets.GITOPS_REPOS }}
    outputs:
      matrix-repos: ${{ steps.repos.outputs.SOLUTIONS }}
    steps:

      - name: Checkout GitOps
        uses: actions/checkout@v3

      - run: echo $(yq -V)

      - name: Get Solution Repo's
        id: repos
        run: |
          repos=$(yq '{"include": .repositories.solutions + .repositories.pipeline + .repositories.deployment }' repositories.yml -o=json | jq -c)
          echo $repos
          echo "SOLUTIONS=$repos" >> $GITHUB_OUTPUT

  make-changes:
    name: Make changes to repos
    needs: [get-config]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-config.outputs.matrix-repos) }}
    permissions: write-all
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Node dependencies
        run: npm install --no-save @actions/core @actions/github

      - name: Check repo exists
        id: repo-exists
        run: .github/actions-scripts/repo-check-exists.mjs
        env:
          GHA_TOKEN: ${{ secrets.SETUP_PAT }}
          REPO_OWNER: ${{ github.repository_owner	 }}
          REPO_NAME: ${{ matrix.repo }}

      - name: Create repo
        if: ${{ steps.repo-exists.outputs.result != true  }}
        run: .github/actions-scripts/repo-check-exists.mjs
        env:
          GHA_TOKEN: ${{ secrets.SETUP_PAT }}
          REPO_TEMPLATE: ${{ matrix.repo-template	 }}
          REPO_OWNER: ${{ github.repository_owner	 }}
          REPO_NAME: ${{ matrix.repo }}
          REPO_DESC: ${{ matrix.repo-description }}

