name: REPOSITORY-VARIABLE-CHANGES
run-name: Event ${{ github.event_name }} run by ${{ github.actor }} 

on:
  workflow_dispatch:

jobs:

  get-config:
    name: Repositories GitOps
    runs-on: ubuntu-latest
    #env:
    #  GH_TOKEN: ${{ secrets.GITOPS_REPOS }}
    outputs:
      matrix-vars: ${{ steps.repos.outputs.VARIABLES }}
    steps:

      - name: Checkout GitOps
        uses: actions/checkout@v3

      - name: Get Solution Repo's
        id: repos
        run: |
          vars=$(yq '{"include": .repo-variables }' repo-variables.yml -o=json | jq -c)
          echo $vars
          echo "VARIABLES=$vars" >> $GITHUB_OUTPUT

  make-changes:
    name: Make changes to repository variables
    needs: [get-config]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-config.outputs.matrix-vars) }}
    permissions: write-all
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Node dependencies
        run: npm install --no-save @actions/core @actions/github

      # - name: Check variables exists
      #   id: repo-exists
      #   run: .github/actions-scripts/repo-check-exists.mjs
      #   env:
      #     GHA_TOKEN: ${{ secrets.SETUP_PAT }}
      #     REPO_OWNER: ${{ github.repository_owner	 }}
      #     REPO_NAME: ${{ matrix.repo }}

      - name: Create variables
        run: .github/actions-scripts/repo-create-variable.mjs
        env:
          GHA_TOKEN: ${{ secrets.SETUP_PAT }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ matrix.repo }}
          VAR_NAME: ${{ matrix.name }}
          VAR_VAL: ${{ matrix.value }}

      - name: GHA Summary
        run: echo "Variable ${{ matrix.name }} created/updated" >> $GITHUB_STEP_SUMMARY