name: REPOSITORY-CHANGES
run-name: Something

on:
  workflow_dispatch:

jobs:

  get-config:
    name: Repositories GitOps
    runs-on: ubuntu-latest
    #env:
    #  GH_TOKEN: ${{ secrets.GITOPS_REPOS }}
    outputs:
      matrix-solutions: ${{ steps.solution-repos.outputs.SOLUTIONS }}
    steps:

      - name: Checkout GitOps
        uses: actions/checkout@v3

      - run: echo $(yq -V)

      - name: Get Solution Repo's
        id: solution-repos
        run: |
          soln=$(yq '{"include": .repositories.solutions }' repositories.yml -o=json | jq -c)
          echo $soln
          echo "SOLUTIONS=$soln" >> $GITHUB_OUTPUT

  make-changes:
    name: Make changes to repos
    needs: [get-config]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-config.outputs.matrix-solutions) }}
    permissions: write-all
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install Node dependencies
        run: npm install --no-save @actions/core @actions/github

      - name: Get repo
        id: repos-get
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/actions-scripts/repos-get.mjs

      # - name: Check repo exists
      #   uses: actions/github-script@v7
      #   id: exists
      #   with:
      #     #result-encoding: string
      #     debug: true
      #     script: |
      #       await github.rest.repos.get({
      #         owner: 'dr3dr3',
      #         repo: 'base-gitops'
      #       });
      #       console.log('test')

      - name: Result
        run: echo '{ ${{ steps.repos-get.outputs.repo }} }'

      - name: Console Log
        run: console.log({ ${{ steps.repos-get.outputs.repo }} })
