name: REPOSITORY-CHANGES
run-name: Something

on:
  workflow_dispatch:

jobs:

  get-config:
    name: Repositories GitOps
    runs-on: ubuntu-latest
    #env:
    #  GH_TOKEN: ${{ secrets.GITOPS_REPOS }}
    outputs:
      matrix-solutions: ${{ steps.solution-repos.outputs.SOLUTIONS }}

    steps:

      - name: Checkout GitOps
        uses: actions/checkout@v3

      - run: echo $(yq -V)

      - name: Get Solution Repo's
        id: solution-repos
        run: |
          soln=$(yq '{"include": .repositories.solutions }' repositories.yml -o=json | jq -c)
          echo $soln
          echo "SOLUTIONS=$soln" >> $GITHUB_OUTPUT

  make-changes:
    name: Make changes to repos
    needs: [get-config]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-config.outputs.matrix-solutions) }}

    steps:

      - name: Check repo exists
        uses: actions/github-script@v7
        id: exists
        with:
          script: |
            github.rest.repos.get({
              owner: 'dr3dr3',
              repo: 'base-gitops',              
            })

      - name: Get result
        run: echo "${{ steps.exists.outputs.result }}"


        # '{"include":[{"name":"start","repo":"base-start"},{"name":"test","repo":"base-start"}]}'